[package]

name = "rustache"
version = "0.0.1"
authors = ["Jarrod Ruhland <jarrod.ruhland@gmail.com>"]

[lib]

name = "rustache"
path = "src/lib.rs"

[dependencies]
regex = "*"
rustc-serialize = "*"

[dependencies.memstream]
git = "https://github.com/singpolyma/rust-memstream.git"
branch = "fix-for-rust-stable"
